version: '3.4'

services:
  webhook:
    image: ${DOCKER_REGISTRY-}webhook
    build:
      context: .
      dockerfile: WebHook/Dockerfile
    ports:
      - '0.0.0.0:443:443'
      - '0.0.0.0:80:80'



